#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple-ap1"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region ca-central-1 \
--stack-name $STACK_NAME